const server = require('./server');
const router = require('./router');
const requestHandlers = require('./requestHandlers');
const dbCreate = require('./lib/database').create;
const dotenv = require('dotenv');
dotenv.config();
let handle = {};
handle['/'] = requestHandlers.start;
handle['/start'] = requestHandlers.start;
handle['/dataService'] = requestHandlers.dataService;
let db = [dbCreate(0), dbCreate(1)];
server.start(router.route, handle, db);